INSERT INTO books (
    isbn,
    title,
    author,
    genre_id,
    publisher,
    publication_date,
    language,
    pages,
    price,
    total_copies,
    available_copies,
    description,
    cover_image_url,
    active,
    created_at,
    updated_at
) VALUES

      (
          '9780439708180',
          'Harry Potter and the Sorcerer''s Stone',
          'J.K. Rowling',
          (SELECT id FROM genres WHERE code = 'FANTASY'),
          'Bloomsbury',
          '1997-06-26',
          'English',
          309,
          19.99,
          10,
          10,
          'A young wizard discovers his magical heritage and attends Hogwarts School of Witchcraft and Wizardry.',
          'https://covers.openlibrary.org/b/id/7984916-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780451524935',
          '1984',
          'George Orwell',
          (SELECT id FROM genres WHERE code = 'SCIENCE_FICTION'),
          'Secker & Warburg',
          '1949-06-08',
          'English',
          328,
          14.99,
          8,
          8,
          'A dystopian novel set in a totalitarian society under constant surveillance.',
          'https://covers.openlibrary.org/b/id/7222246-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780061120084',
          'To Kill a Mockingbird',
          'Harper Lee',
          (SELECT id FROM genres WHERE code = 'FICTION'),
          'J.B. Lippincott & Co.',
          '1960-07-11',
          'English',
          281,
          12.99,
          6,
          6,
          'A novel about racial injustice and moral growth in the American South.',
          'https://covers.openlibrary.org/b/id/8228691-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780307474278',
          'The Girl with the Dragon Tattoo',
          'Stieg Larsson',
          (SELECT id FROM genres WHERE code = 'MYSTERY'),
          'Norstedts Förlag',
          '2005-08-01',
          'English',
          465,
          16.50,
          5,
          5,
          'A journalist and a hacker investigate a decades-old disappearance.',
          'https://covers.openlibrary.org/b/id/8231856-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780140449136',
          'The Odyssey',
          'Homer',
          (SELECT id FROM genres WHERE code = 'HISTORY'),
          'Penguin Classics',
          '1996-11-01',
          'English',
          560,
          18.00,
          4,
          4,
          'The epic journey of Odysseus returning home after the Trojan War.',
          'https://covers.openlibrary.org/b/id/8231990-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780590353427',
          'Matilda',
          'Roald Dahl',
          (SELECT id FROM genres WHERE code = 'CHILDREN'),
          'Puffin Books',
          '1988-10-01',
          'English',
          240,
          9.99,
          7,
          7,
          'A brilliant young girl with telekinetic powers stands up to cruel adults.',
          'https://covers.openlibrary.org/b/id/8225632-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780140449266',
          'Meditations',
          'Marcus Aurelius',
          (SELECT id FROM genres WHERE code = 'PHILOSOPHY'),
          'Penguin Classics',
          '2006-05-30',
          'English',
          304,
          13.50,
          6,
          6,
          'Personal reflections on Stoic philosophy by the Roman emperor.',
          'https://covers.openlibrary.org/b/id/8235216-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      ),

      (
          '9780062316097',
          'The Alchemist',
          'Paulo Coelho',
          (SELECT id FROM genres WHERE code = 'FICTION'),
          'HarperOne',
          '1993-05-01',
          'English',
          208,
          11.99,
          10,
          10,
          'A philosophical story about following your dreams.',
          'https://covers.openlibrary.org/b/id/8275320-L.jpg',
          1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
      );
